# Licensed to the .NET Foundation under one or more agreements. The .NET Foundation licenses this file to you under the MIT license. See the LICENSE.md file in the project root for more information.

# Name: DotNet-Project-System-PR
# URL: https://dev.azure.com/dnceng/public/_build?definitionId=406

# Validates commits as part of GitHub pull requests.

###################################################################################################################################################################
# PIPELINE METADATA
###################################################################################################################################################################

# Activates the pipeline for every commit on a PR.
# See: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema/pr?view=azure-pipelines
pr:
  branches:
    include:
    - main
    - feature/*
  paths:
    exclude:
    - docs/*
    - README.md

pool:
  # The max number of concurrent jobs that can be run in the pool is 820.
  # https://dnceng.visualstudio.com/public/_settings/agentqueues?queueId=396&view=jobs
  name: NetCore1ESPool-Public
  # Demands Docs: https://docs.microsoft.com/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml#manually-entered-demands
  # ImageOverride is used to select the image. See:
  # - https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/510/1ES-Hosted-Pools-Migration
  # - https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/675/1ESManagedPoolsDesign?anchor=1es-managed-images
  # Image List: https://helix.dot.net/#1esPools
  demands: ImageOverride -equals Build.Windows.Amd64.VS2022.Pre.Open

variables:
  # # The max number of concurrent jobs that can be run in the pool is 820.
  # # https://dnceng.visualstudio.com/public/_settings/agentqueues?queueId=396&view=jobs
  # DefaultPoolName: NetCore1ESPool-Public
  # # https://docs.microsoft.com/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml#manually-entered-demands
  # # Image List: https://helix.dot.net/#1esPools
  # # DefaultDemands: ImageOverride -equals Windows.VS2022Preview.Amd64.Open
  # DefaultDemands: ImageOverride -equals Build.Windows.Amd64.VS2022.Pre.Open

  # https://docs.microsoft.com/dotnet/core/tools/dotnet-environment-variables#dotnet_skip_first_time_experience
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # https://docs.microsoft.com/dotnet/core/tools/dotnet-environment-variables#dotnet_nologo
  DOTNET_NOLOGO: true
  # Opt out of automatically injecting Codesign Validation into the pipeline.
  # See: https://aka.ms/gdn-injection
  runCodesignValidationInjection: false
  # Suspend enforcement of NuGet Single Feed Policy. See:
  # - https://aka.ms/nugetmultifeed
  # - https://docs.opensource.microsoft.com/tools/nuget_security_analysis/nuget_security_analysis/
  # - https://docs.opensource.microsoft.com/tools/cg/how-to/nuget-multifeed-configuration/
  # - https://onebranch.visualstudio.com/OneBranch/_wiki/wikis/OneBranch.wiki/5205/TSG-Build-Broken-Due-to-Using-Multiple-Feeds?anchor=setting-nugetsecurityanalysiswarninglevel-in-cdp
  NugetSecurityAnalysisWarningLevel: none

# parameters:
#   # Pool information is needed to be passed to every job as a parameter.
#   # If a pipeline variable is used instead of a job parameter, it won't be evaluated at compile-time, and the variable will evaluate as empty string. Thus, a random pool and demands will be used since no value is provided.
#   # If we define the pool information as a pipeline parameter object, we can simply pass a single parameter to every job instead of passing the pool name and demands separately.
#   - name: DefaultPool
#     type: object
#     default:
#       # The max number of concurrent jobs that can be run in the pool is 820.
#       # https://dnceng.visualstudio.com/public/_settings/agentqueues?queueId=396&view=jobs
#       name: NetCore1ESPool-Public
#       # Demands Docs: https://docs.microsoft.com/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml#manually-entered-demands
#       # ImageOverride is used to select the image. See:
#       # - https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/510/1ES-Hosted-Pools-Migration
#       # - https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/675/1ESManagedPoolsDesign?anchor=1es-managed-images
#       # Image List: https://helix.dot.net/#1esPools
#       demands: ImageOverride -equals Build.Windows.Amd64.VS2022.Pre.Open

###################################################################################################################################################################
# STAGES
###################################################################################################################################################################

stages:
- stage: Build
  displayName: Build
  jobs:
  - template: templates/build-pull-request.yml
    parameters:
      BuildConfiguration: Debug
      ArtifactName: '$(Build.BuildNumber)-Debug'
  - template: templates/build-pull-request.yml
    parameters:
      BuildConfiguration: Release
      ArtifactName: '$(Build.BuildNumber)'

- stage: PostBuild
  displayName: Post-Build
  dependsOn: Build
  variables:
    BuildConfiguration: Release
    # Disables the TSA compliance results upload task in analyze-compliance.yml.
    UploadTSAResults: false
    # Disables the signing validation tasks within analyze-compliance.yml.
    VerifySigning: false
  jobs:
  - template: templates/analyze-compliance.yml
  - template: templates/publish-richnav.yml