# Licensed to the .NET Foundation under one or more agreements. The .NET Foundation licenses this file to you under the MIT license. See the LICENSE.md file in the project root for more information.

stages:
# This template is provided by the DartLabOptProfTemplates repo, declared in the resources section of official.yml.
- template: \templates\stages\visual-studio\single-runsettings.yml@DartLabOptProfTemplates
  parameters:
    name: GenerateOptimizations
    displayName: Generate Optimizations
    dependsOn:
    - Publish
    - Compliance
    runSettingsURI: https://vsdrop.corp.microsoft.com/file/v1/RunSettings/$(System.TeamProject)/dotnet/project-system/$(Build.SourceBranchName)/$(Build.BuildId);OptProf.runsettings
    visualStudioBootstrapperURI: $(visualStudioBootstrapperURI)
    optOptimizationInputsDropName: OptimizationInputs/$(Build.ProjectName)/$(Build.Repository.Name)/$(Build.SourceVersion)/$(Release.ReleaseId)/$(Release.EnvironmentId)/$(Release.AttemptNumber)
    testLabPoolName: VS-Platform
    # preDeployAndRunTestsStepList:
    # - download: ComponentBuildUnderTest