name: markdown-link-check
on: [push, pull_request]

jobs:
  markdown-link-check:
    name: markdown-link-check
    runs-on: ubuntu-latest

    steps:
    - name: Clone the repository
      uses: actions/checkout@v3

    - name: Validate Markdown links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        # https://github.com/tcort/markdown-link-check#config-file-format
        config-file: '.github/workflows/markdown-link-check-config.json'