name: Post PRs and issues to Teams

on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Notify
        uses: davidwengier/PostAdaptiveCard@v1.0.0
        with:
          webhook-uri: https://outlook.office.com/webhook/4ba7372f-2799-4677-89f0-7a1aaea3706c@72f988bf-86f1-41af-91ab-2d7cd011db47/IncomingWebhook/574a9caf099746e480b30f29d5dfadc2/9dbc0cfc-eab3-42c9-838a-4879bef6875e