name: Post PRs and issues to Teams

on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Notify
        uses: davidwengier/PostAdaptiveCard@v1.0.1
        env:
          WEBHOOK_FROM_SECRET: ${{ secrets.TeamsWebhook }}
        with:
          webhook_uri: ${WEBHOOK_FROM_SECRET}
